Internet_banking_system/Internet_banking_system/Models/ErrorViewModel.cs
namespace Internet_banking_system.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Internet_banking_system/Internet_banking_system/Areas/Admin/Controllers/CustomerController.cs
using Internet.Banking.Application.Abstraction;
using Internet.Banking.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Internet.Banking.Infrastructure.Database;

namespace Internet_banking_system.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CustomerController : Controller
    {
        ICustomerAppService _customerAppService;
        public CustomerController(ICustomerAppService customerAppService)
        {
            _customerAppService = customerAppService;
        }
        public IActionResult Index()
        {
            IList<Customer> customers = _customerAppService.Select();
            return View(customers);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            _customerAppService.Create(customer);
            return RedirectToAction(nameof(CustomerController.Index));
        }
        public IActionResult Delete(int id)
        {
            bool deleted = _customerAppService.Delete(id);

            if (deleted)
            {
                return RedirectToAction(nameof(CustomerController.Index));
            }
            else
                return NotFound();
        }
        public IActionResult Update(int id)
        {
            Customer customer = _customerAppService.Update(id);
            return View(customer);
        }

        [HttpPost]
        public IActionResult Update(Customer customer)
        {
            _customerAppService.Update(customer);
            return RedirectToAction(nameof(CustomerController.Index));
        }

    }
}

Internet_banking_system/Internet_banking_system/Controllers/HomeController.cs
using Internet.Banking.Application.Abstraction;
using Internet.Banking.Application.ViewModels;
using Internet_banking_system.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Internet_banking_system.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        IHomeService _homeService;



        public HomeController(ILogger<HomeController> logger, IHomeService homeService)
        {
            _logger = logger;
            _homeService = homeService;
        }

        public IActionResult Index()
        {
            CarouselCustomerViewModel viewModel = _homeService.GetIndexViewModel();
            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Internet_banking_system/Internet_banking_system/Areas/Admin/Views/Customer/Create.cshtml
@model Customer

@{
    ViewData["Title"] = "Customer - Create";
}
<h1>@ViewData["Title"]</h1>

<form asp-action="Create" method="post">
    <div class="mb-3">
        <label class="form-label" asp-for="CustomerName"></label>
        <input class="form-control" asp-for="CustomerName">
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="CustomerSurname"></label>
        <input class="form-control" asp-for="CustomerSurname">
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="CustomerPhone"></label>
        <input class="form-control" asp-for="CustomerPhone">
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="CustomerEmail"></label>
        <input class="form-control" asp-for="CustomerEmail">
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="CustomerAdress"></label>
        <input class="form-control" asp-for="CustomerAdress">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Internet_banking_system/Internet_banking_system/Areas/Admin/Views/Customer/Index.cshtml
@model IList<Customer>


@* "@{}" This code block is used to write C# code within your view 
	In this code block, you are setting the value of the "Title" key in the "ViewData"
	dictionary to "Customer Administration"
*@
@{
	ViewData["Title"] = "Customer Administration";
}
@*This line is responsible for rendering the value of the "Title" key from 'ViewData' within an
	<h1> HTML Element
*@
<h1>@ViewData["Title"]</h1>



@{
    if (Model != null && Model.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">@nameof(Customer.Id)</th>
                    <th scope="col">@nameof(Customer.CustomerName)</th>
                    <th scope="col">@nameof(Customer.CustomerSurname)</th>
                    <th scope="col">@nameof(Customer.CustomerPhone)</th>
                    <th scope="col">@nameof(Customer.CustomerEmail)</th>
                    <th scope="col">@nameof(Customer.CustomerAdress)</th>
                    <th scope="col">Delete</th>
                    <th scope="col">Update</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; ++i)
                {
                    <tr>
                        <th scope="row">@Model[i].Id</th>
                        <td>@Model[i].CustomerName</td>
                        <td>@Model[i].CustomerSurname</td>
                        <td>@Model[i].CustomerPhone</td>
                        <td>@Model[i].CustomerEmail</td>
                        <td>@Model[i].CustomerAdress</td>
                        <td><a asp-action="Delete" asp-route-id="@Model[i].Id" onclick="return ConfirmDelete();">Delete</a></td>
                        <td><a asp-action="Update" asp-route-id="@Model[i].Id" onclick="return ConfirmUpdate();">Update</a></td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

<button type="button" class="btn btn-dark" onclick="window.location.href = '@Url.Action("Create")'">Create Customer</button>


@section Scripts
    {
    <script src="~/js/dialogs.js"></script>
}

Internet_banking_system/Internet_banking_system/Areas/Admin/Views/Customer/Update.cshtml
@model Customer

@{
    ViewData["Title"] = "Customer - Update";
}
<h1>@ViewData["Title"]</h1>

<form method="post">
    <div asp-action="Update">
        <input class="form-control" asp-for="Id" type="hidden">
        <div class="mb-3">
            <label class="form-label" asp-for="CustomerName"></label>
            <input class="form-control" asp-for="CustomerName">
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="CustomerSurname"></label>
            <input class="form-control" asp-for="CustomerSurname">
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="CustomerPhone"></label>
            <input class="form-control" asp-for="CustomerPhone">
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="CustomerEmail"></label>
            <input class="form-control" asp-for="CustomerEmail">
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="CustomerAdress"></label>
            <input class="form-control" asp-for="CustomerAdress">
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <button type="submit" class="btn btn-primary form-control">Submit</button>
        </div>
        <div class="col-6">
            <a asp-controller="Customer" asp-action="Index" class="btn btn-secondary border form-control ">
                Back to list
            </a>
        </div>
    </div>
    
</form>

Internet_banking_system/Internet_banking_system/Views/Home/Index.cshtml
@model CarouselCustomerViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Internet Banking</h1>
</div>

@{
    if (Model != null && Model.Carousels != null && Model.Carousels.Count > 0)
    {
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">

                @for (int i = 0; i < Model.Carousels.Count; ++i)
                {
                    string active = String.Empty;
                    if (i == 0)
                        active = "active";

                    <div class="carousel-item @active">
                        <img src="@Model.Carousels[i].ImageSrc" class="d-block w-100" alt="@Model.Carousels[i].ImageAlt">
                    </div>
                }

            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    }
}
@section Styles
    {
    <link rel="stylesheet" href="~/css/shop_home.css" asp-append-version="true" />
}

Internet_banking_system/Internet_banking_system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Internet_banking_system</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Internet_banking_system.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Internet_banking_system</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                                <li><a class="dropdown-item active" asp-area="Admin" asp-controller="Customer" asp-action="Index">Customer</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item disabled" href="#">Transakce</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item disabled" href="#">Účty</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item disabled" href="#">Hlášení</a></li>
                            </ul>
                        </div>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <!-- Login Form -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="loginDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Login
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="loginDropdown">
                                <form class="px-4 py-3">
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <input type="text" class="form-control" id="username" placeholder="Username">
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control" id="password" placeholder="Password">
                                    </div>
                                    <button type="submit" class="btn btn-primary">Sign in</button>
                                </form>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Forgot Password?</a>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Internet_banking_system - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>